project:
  type: book
  output-dir: _site

book:
  title: "PT-Notes"
  chapters:
    - index.qmd
    - 软件.qmd
    - 测量方法.qmd
    - 装置搭建和控制.qmd
    - 拍摄.qmd
    - 数据处理.qmd
    - 杂七杂八.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  latex:
    toc: true
    documentclass: scrreprt
    pdf-engine: xelatex
    include-in-header:
      - text: |
          \usepackage{ctex}
