# 拍摄和视频追踪

拍摄和视频追踪是 PT 中最常用的一种实验方法，一般而言，我们需要从视频中追踪某些标记点，从而得到物体的位置、角度形变和运动状态随时间的变化关系，但其精度很大取决于实验时拍摄相关的参数和环境. 实验设计时应考虑相机、光照、标定和后续追踪方法.

## 拍摄

### 相机选取

**手机**：最常见的拍摄设备，人手一个. 但在使用时需要注意：

- 尽量进入专业模式人工设置拍摄参数，而不是全部交给自动设置
- 注意手机视频可能采用可变帧率(VFR)，也就是每一帧的时间间隔可能不同，最好能设置为固定帧率(CFR). 假设不能设置或找不到相关设置，需要在 FFmpeg 等重新转码成固定帧率（当然，帧率间隔不同带来的误差是消除不了的）
- 部分手机存在较明显的滚动快门效应，最好拍摄时运动方向和快门滚动方向一致
- 手机的高速摄像等很多时候是 AI 插帧算出的，不可信（除非你用的是索尼 Xperia XZ1，这个确实是实打实原生 960 帧）

**高速摄像**：除开手机外，实验中最常用的拍摄设备. 实验室的高速摄像最高在 1000 帧/秒（网络黑白的可以到更高，但用起来不太方便）. 使用时需要注意：

- 高速摄像最大的优势是时间分辨率高，但帧率越高通常意味着单帧进光量越少，因此不应盲目使用最高帧率，而应根据待研究现象的特征时间尺度选择
- 高速摄像非常依赖照明。曝光时间缩短以后，单帧进光量会迅速下降，因此需要使用较强且稳定光源
- 高速摄像一般具有时间限制，只能拍摄几秒，对于部分网络高速摄像机可以通过减小 ROI 换取更长的拍摄时间，但总之是有限的，需要在拍摄帧率和拍摄时长之间进行权衡
- 高速摄像的拍摄帧率和最后视频导出帧率往往不同，比如 1000 帧拍摄的视频，导出视频往往是 50 帧，也就是导出视频慢放了 20 倍，追踪时需要注意这一点

**微距相机**：适合毫米甚至更小尺度的物体，例如细线、颗粒、液滴、小幅振动和材料表面等的拍摄

- 微距镜头的景深通常较浅，被测物体稍微沿光轴方向移动就可能失焦，因此应尽量保证运动发生在同一焦平面附近
- 微距下相机自身极小的振动也可能对应明显的像素位移，因此相机和实验装置都应牢固固定或者等待稳定后再拍摄和测量
- 标尺与被测物体处于同一平面，避免纵深视差（近大远小）

**远心镜头相机**：一种特殊的相机，通过特殊的镜头结构，只允许平行光通过，从而消除拍摄中的透视效应（没有近大远小），因此特别适合精确测量三维物体的形状或尺寸变化

**热成像**：适合测量温度场、热传导、对流以及材料受热后的温度变化. 拍摄相关的参数设置和其他相机基本相同，这里不过多赘述. 温度测量相关的参数设置见实验测量方法相关章节.

### 相机参数

拍摄时合理的参数设置往往能使得拍摄清晰锐利，使得后续追踪更加方便和精确. 根据笔者个人的经验，相机调整一般按照拍摄位置、焦距、帧率、快门速度、光圈、ISO、白平衡等的顺序进行设置，下面给出每一个参数的说明和建议：

**拍摄位置**：拍摄时相机的光轴应该垂直于物体运动平面，从而避免梯形透视（可以在不同位置放置标尺，测量相同长度的像素数量，从而说明已经消除了梯形透视，这部份内容可以放附录补充说明）. 长度标尺最好和物体运动平面共面. 消除透视带来偏差.

**焦距**：焦距决定相机的视场大小和透视程度，一般而言，广角镜头能够拍摄更大的范围，但往往具有明显的镜头畸变和；长焦镜头视场较小，但对于实验测量比较友好（畸变小），因此实验中常用. 另外，变焦一定要是光学变焦，数码变焦（手机大部分是数码变焦）本质是裁切像素放大，这种放大没有意义.

**帧率**：帧率决定拍摄视频的时间分辨率，帧率越高，快门速度越短，单帧进光量越小，需要的打光越亮，可以拍摄的时长越短，同时后续数据处理越慢，因此没必要无上限追求高帧率. 不过对帧率需求没有预期的情况下，也可以先直接使用最高的帧率拍摄观察过程，毕竟高帧率可以非常容易变成低帧率，但反之不行.

**快门速度**：快门速度决定单帧曝光的时间，注意这和帧率是两个不同的概念，帧率决定的是两帧之间的间隔时间. 快门速度的上限是帧率的倒数. 我们拍摄物体运动时出现残影，往往是因为快门速度不够快，物体在单帧曝光时运动了较远的距离，从而出现残影. 因此，要消除残影，本质是要调高快门速度，而与帧率无关（省赛时有很多队伍混淆了快门速度和帧率这两个概念，认为要消除残影需要更高帧率，虽然高帧率也可以消除残影，但本质是高帧率需要高快门速度）.

**光圈**：光圈主要影响进光量和景深. 光圈越大，进入相机的光越多，但景深越浅，使得物体光轴方向上有小的偏移，就会有明显的虚焦. 光圈越小，进入相机的光越少，但景深越大，物体即使稍微偏离对焦距离，也不会明显模糊. 对于物体的追踪，有时我们难以控制物体在光轴方向的运动，此时就需要减小光圈.

**ISO**：ISO 可以理解为相机对传感器信号的放大程度. 提高 ISO 可以使画面变亮，但同时会放大噪声. 对于追踪而言，噪声往往会影响边缘识别，因此最好在曝光足够的前提下尽量使用较低 ISO，而不是依靠高 ISO 强行提高亮度.

**白平衡，对比度等**：这些参数主要影响视频的色彩和对比度，对于追踪而言，这些参数一般不需要特别调整，并且这部份参数可以拍摄后再进行设置. 不过，有时手动调整白平衡和对比度能提高物体和标记点与背景的区分度，使得追踪更容易.

一般而言，拍摄位置、焦距、帧率会根据实验要求而进行设定，快门速度调整到整个运动过程中没有明显残影. 此时相机的亮度需求基本确定，从而再进行打光. 假设打光有限制，亮度不够，先考虑增大光圈，如果光圈已经最大，再考虑提高 ISO 以及降低快门速度. ISO 和快门速度需要我们平衡残影和噪点对追踪带来的影响哪一个更大. 当然，最好的方式还是能打更亮的光，使得二者兼顾.

### 双机位拍摄

当物体具有明显三维运动时，单个相机只能得到运动在成像平面上的投影，因此可以使用两个相机从不同方向同时拍摄，例如一个拍摄正面，一个拍摄侧面，从而能真正实现物体三维运动的重建. 

双机位拍摄最重要的一点是两个相机的拍摄必须严格同步，这在实际操作中非常困难. 因此，实际上更容易实现的方案是使用镜子进行双机位拍摄. 通过在实验区域旁放置镜子，使同一个画面同时包含物体本身和镜像，从而用一台相机同时获得两个视角.

- 镜子应尽量平整并牢固固定
- 直接画面和镜像画面需要分别进行标定
- 镜像坐标存在翻转，后期需要进行处理

## 提升追踪精确度

**选取更好标记方式**：合理设计追踪标记通常比后期再使用复杂算法进行追踪更加有效. 其原则是让真正需要追踪的位置在视频中具有稳定、明显且容易识别的特征. 常见的有下面几种方法：

- 在物体上使用颜色显著的标记：在物体上粘贴红色、绿色、黑色等与背景反差明显的圆点或色块，这也是实验中最常用的方法.
- 荧光标记：对于复杂背景或者普通颜色对比度不足的情况，可以尝试使用荧光材料+黑暗背景，亦或者使用特定波长的荧光材料+特定波长的滤光片，从而将待测点和背景区分开来，提升信噪比.
- 背光拍摄：如果只需要物体的轮廓，可以不使用表面标记，直接在物体背后设置均匀光源，将目标拍成高对比度剪影
- ArUco 等编码标记：可以使用 ArUco、AprilTag 等编码标记. 相比单个色点，这类标记不仅能够识别位置，还能够识别方向，同时在 OpenCV 中相关标记识别一般比色点更准确

标记并不是越小越好. 如果一个标记在视频中只有 2~3 pixel，那么轻微噪声就可能导致质心位置明显变化. 一般希望标记在画面中至少具有数个到十几个像素的尺度，在保证不会遮挡实验现象的情况下可以适当增大.

**合适打光**：打光对于视频追踪的重要程度实际上不亚于相机拍摄本身. 理想的打光应该使得亮度均匀，能在镜头中清晰呈现物体（尤其是高速摄像等吃光照强度的情况）. 打光主要分为两种：点光源（灯泡）、面光源（LED 灯板）. 其主要特性如下：

**点光源**：点光源容易实现很高的亮度，但会出现阴影和高光，对追踪造成影响，打光时需要考虑将阴影和高光放在不影响追踪的区域，或者使用多个点光源打光、将光源放置在更远处（光源越远，打光越均匀）从而减小阴影和高光的影响.

**面光源**：面光源照明更加均匀，阴影较弱，因此通常更加适合定量视频追踪. 如果面光源亮度足够，最好使用面光源进行打光保证背景亮度均匀性.

同时，拍摄时还需要考虑频闪问题，现代相机一般有抗频闪功能（手机一般默认开启），可能需要进行设置.

**特定追踪标记**：如果实验对象允许粘贴较大的编码标记，ArUco 或 AprilTag 往往是非常方便的方法. 一个标记就能够同时得到：

- 中心位置
- 四个角点的位置
- 平面内旋转角度
- 标记 ID

如果进行相机标定并且已知标记实际尺寸，还可以进一步估计标记相对于相机的三维姿态. 因此对于刚体平移+旋转问题，这类标记通常比同时设置多个普通颜色点更加方便. 相关编码识别在 Python + OpenCV 中非常容易实现，使用这类标记也可以省去手动标记点的时间，同时识别精度也比标记+Tracker 好. 缺点是标记需要占据一定面积，并不适合非常小的实验对象.

**视频预处理再追踪**：实际追踪并不一定需要直接在原始彩色视频上进行. 很多情况下，先对图像进行适当预处理能够显著提高追踪稳定性. 但预处理的原则应当是 增强已经存在的信息，而不是创造新的信息. 过度锐化、AI 超分辨率、AI 插帧等方法可能生成并不存在的细节，因此一般不建议用于定量实验. 常见的预处理方法包括：

- 裁剪 ROI：裁剪视频，去除无关背景干扰
- 灰度化和颜色空间转换：将视频转换为灰度图像，或者进行颜色空间转换（如 HSV），从而提取出某一个颜色通道的信息，筛出标记
- 边缘和梯度：如果需要追踪的是物体轮廓而不是某个颜色区域，可以首先计算图像梯度或者使用 Canny 等边缘检测算法. 例如一根细线和背景之间存在明显亮度变化时，直接追踪线本身可能比较困难，而追踪线两侧的亮度梯度峰值反而更加准确.
- 二值化：将视频转换为二值图像，通过阈值分割提取标记
- 形态学操作：二值化以后可能存在一些孤立的小噪点或者目标内部的小孔洞，可以使用开运算和闭运算进行处理. 开运算用于去除孤立的小噪点、闭运算用于填补目标内部的小缺口

这些视频预处理方法可以同时使用，比如可以先裁剪 ROI 后进行边缘和梯度提取，从而进行二值化，再进行形态学处理. 相关的操作很容易通过 Python + OpenCV 实现. 
  
