# 常用软件

这里列举出了 PT 比赛中常用的工具，软件，以及一些个人的经验.

## AI 工具

AI 时代最常用的工具软件一定是各类 AI 工具，因此这里介绍笔者比赛中比较好用的各类 AI 软件.

注意：由于 AI 领域发展飞快，因此这里所提及的各类模型优缺点可能在模型和工具更新后有所变化，（写于 2026-8-16）甚至于考虑到 PT 竞赛可能持续将近整整一年，随着时间变化各类模型和工具的能力可能也会发生较大变化，这里仅作为参考.

**ChatGPT + Codex**：区国赛用的最多的模型，数学物理能力非常强，同时对于写代码的能力也足够（他的 Oneshot 能力出色，也就是完全从零开始，提出要求，让他写代码的情况很不错，但对于现有代码的修改，尤其是之前自己写或其他模型写的代码，则容易出现“过度”修改）. 同时相对而言，国内用户使用相比 Claude 比较方便，薅第一个月 Pro 会员或折腾中转等价格也不算非常贵. 因此截止文章写的时候，这是我最推荐的模型.

**Claude**：世界顶尖的模型之一，模型能力很强，但由于其公司 Anthropic 天天整烂活，对中国用户及其不友好，加上个人认为其数学物理能力比不上 GPT，因此这里个人不做推荐. 但鉴于其本身也确实是世界顶尖的模型，因此列在这里. 

**Deepseek**：国内非常好用的模型，便宜大碗，之前搭配 OpenCode 作为 Agent，GPT 5.6 出来后作为 GPT 5.6 的 SubAgent 模型搭配使用. 近期 Deepseek V4 Pro + Deepseek Harness 非常惊艳，基本能达到 GPT 和 Claude 的顶尖水平（不过需要折腾，同时由于出的较晚，笔者打 PT 时没用过 DSv4 + DSH）. 假设其他模型使用上存在困难（不方便访问，价格过高等），完全可以使用 DS 系列模型进行替换.

**Gemini**：知识库很全，Deep Research 能搜集到非常多冷门的文献，曾经 Gemini 3 Pro 非常惊艳，加上之前学生一美元一年 Pro 会员的优惠非常好用，但随着其他 AI 厂商的模型更新，以及 Gemini 后期逐渐“降智”，现在 Gemini 已经不太推荐使用了.

---

其他模型我更多只是临时搜索查询的时候使用，对其能力没有过多了解. 无论对于哪一个 AI，我们主要用于下面工作的辅助：

- 资料收集，文献阅读，现有理论理解
- 公式推导，模型讨论
- 代码编写和修改
- 实验仪器使用说明搜索，实验方案设计研讨
- 实验数据后处理
- PPT 文字优化，讲稿优化
- ......


这里需要注意，对于 AI 生成的内容，我们不能完全直接相信，对于理论等，假设本身了解程度也不是很多，可以尝试使用另一个 AI 检查纠正，同时，对于其建立的模型也应与我们的实际情况进行检查（有些时候说是一样的模型，但式子中偷偷换了一个更简化的情况）.

对于实验方案，代码编写等，AI 很多时候并不知道实验的难易程度，经常会给出说起来轻巧，但实际非常难以实现的实验方案，这需要我们对其给出的实验方案有一定的评估，而不是直接进行（尤其是当你的时间非常紧张的时候）. 同时，有些时候 AI 给出的方案不一定是最优，因此还是希望能有自己的想法，能给出优于 AI 提出的方法.

## 计算

这里的计算主要是已经给出物理模型的微分方程，然后进行数值求解/解析求解. 而纯粹的 3D 建模然后设定参数的模拟见下一章.

**Python**：应该是目前 PT 比赛中最常用的计算程序语言，在区国赛中经常能见到其绘制的图像. 同时本身也非常容易上手. 假设之前没有接触过任何的编程语言，可以考虑接触 Python. 另一方面，AI 写 Python 程序相对其他语言更好，这也是 Python 目前的一个非常大的优势.

**Matlab**：老牌的常用于分析和计算的软件，工具包比较多，文档也比较详细. 但笔者用的不多，很多工具在 Python 中其实也有对应，因此这里不做过多介绍.

**Comsol**：Comsol 更多时候是作为模拟工具，但有时也可以用于理论的数值计算. 比如理论中可能会出现某些曲面积分或者体积分，如果使用前面的编程语言写代码求解需要你自己对曲面或体积划分网格求解，这一般比较麻烦（同时如果写的比较随意没有优化的意识，求解可能很慢）. 因此，我们可以在 Comsol 中将你需要的区域建模出来，并设置需要计算的积分区域和积分函数，从而使用商业成熟的求解器求解. 但这一方法的局限性在于不是很灵活，同时需要了解 Comsol 相关的各种数学算子（ 很多时候单纯的积分只是理论方程求解的一部分）以及 Comsol 模拟的整体逻辑. 这里笔者比较喜欢的方式是使用 Comsol 先把需要的量全部扫描求解出来，再使用 Python 等进行下一步计算.

**Mathematica**：前 AI 时代推导解析公式的非常好用的软件，可以输入微分方程或者积分式子，并得到解析的式子（如果可以给出）. 不过现在大多数时候都直接问 AI，因此这个工具用的少一些. 不过可以使用 AI 生成 MMA 代码或者直接使用 AI 操作 MMA 来保证 AI 数学推导过程中的正确性.

## 模拟

模拟一般用于求解理论中有些难以给出解析求解的部分（比如某个形状在某个流场中不同角度下的升力等），或者是补充实验中受限于实验条件下难以进行参量改变的实验（比如我们希望改变材料的某些参数，但我们只找到两三种材料，数据说服力有限），亦或是分析实验中难以直接测量的量（比如材料的应力分布，流场的流速分布等）

有些队伍会直接将模拟作为完整的“理论”，这一点我个人不是很认同. 模拟可以告诉我们“结果是什么”，但往往不容易直接解释“为什么会这样”/ 更好的做法通常是先通过物理图像、数量级估计或简化模型解释主要机制，再利用模拟计算其中难以解析求解的部分.

**Comsol**：PT 比赛中最常用的模拟软件，基于有限元法，可以进行各种物理现象的模拟，包括但不限于热力学，电磁学，结构力学等，而且可以多物理场耦合，比如某个区域的温度分布会影响电磁学参数（比如磁导率），从而影响电磁场分布，Comsol 可以很方便地对这种多物理场耦合的情况联合求解. 但流体相关的 Comsol 模拟比较差. 一些 Comsol 模拟相关的小技巧如下

- 利用对称性简化模型：利用几何、材料和边界条件的对称性，只计算部分区域，可显著减少自由度和计算量
- 合理选取求解域与积分区域：根据物理场特性设置合适的计算域，如磁力计算中，可在磁体外设置一层薄空气域，并在空气域中的闭合曲面上积分 Maxwell 应力张量，避免在材料界面处由于磁场不连续导致计算结果不精确. 在无源空气区域内，由于通量守恒，积分曲面适当移动不改变电磁力
- 局部网格加密：有时我们需要手动划分网格. 在场梯度大、几何尺寸小、材料界面或重点观测区域加密网格，在远离关注区域处使用较粗网格，从而兼顾计算精度和效率. 有时手动划分网格也能规避部分扫描时由于网格划分不同导致的计算结果不一致
- 用参数扫描代替动网格：若只关注不同位置或姿态下的准静态结果，可将位置等作为参数进行扫描，避免网格变形与重构带来的数值误差，并显著降低求解复杂度. 同时，参数扫描的结果经常可以复用，对于同一类情况常常能避免再次计算
- 设置无限元域：对于磁场、电场、声场等理论上延伸至无穷远的物理场，需要在有限计算域外围设置无限元域，将有限区域映射到无穷远. 否则计算结果会受到有限边界的影响
- 进行收敛检查：逐步改变网格尺寸、计算域大小等，检查关键结果是否趋于稳定，这一部分经常作为附录的一部分

**Fluent**：PT 比赛中流体相关的常见的模拟，基于有限体积法. 虽然前面 Comsol 也可以进行流体相关的模拟，但基于有限体积法的 Fluent 相比于基于有限元的 Comsol 天然满足流体的严格局部守恒，同时在流体相关的模拟中也不容易出现数值发散，因此建议流体相关的模拟使用类似 Fluent 的基于有限体积法的求解器,

**自写模拟**：这个一般很少，但有时可能由于前面的求解器比较慢或者计算量比较大，但有时我们并不需要这么高的精度，因此我们需要自己写一些代码进行求解. 此时除开一些常见的求解方法（比如差分法等），我们也可以尝试如 PINN 等基于深度学习的求解方法. 但需要注意的是，对于自写的求解方法，我们应该充分了解其局限性和精度，并先尝试使用一些经典的算例进行验证.

## 绘图

**Origin**：比赛中对于实验数据的绘制基本都是使用 Origin，功能比较全. 比赛中我常使用的绘图参数如下：

- 边框 3 pt，显示上下左右框线，左下主次刻度线朝内，右上不显示刻度线
- 点 9 pt（取决点大小和误差棒大小），误差棒 3 pt，线 3 pt，误差带 70% 透明度
- 理论曲线实线，实验拟合虚线
- 物理量符号斜体，单位正体

**PowerPoint 图形**：在我们的 PPT 中经常需要各种示意图，比如受力分析，光路，实验装置示意图等，绘制这些示意图其实最后发现还是 PPT 的各种形状最方便，而且适合后面进行风格统一和修改调制. 需要善用 PPT 形状中的“组合”和“合并形状”中的“结合”，“组合”，“拆分”等功能

## 视频追踪和测量

**Tracker**：比赛中最常用的测量软件，可以直接从视频中获得位置、速度、角度、周期等随时间变化的数据，可以进行比例尺标定和自动追踪. 一些 Tracker 相关的注意事项如下（拍摄相关的在后续章节中介绍）：

- 标尺最好和被测物体处在同一平面，否则比例尺会产生透视视差（当然这是可以修正的，但需要额外的校正步骤）
- 注意拍摄帧率和 Tracker 设置的帧率相同，尤其是高速摄像. Tracker 默认读取视频格式中的帧率，但对于高速摄像这往往不一致（比如 1000 帧拍摄的视频，导出的视频是 50 帧，也就是慢放 20 倍，Tracker 默认读取 50 帧）. 因此需要在 Tracker 中手动设置实际的帧率
- 自动追踪时合理设置追踪区域、演化率和匹配阈值，可减少背景干扰与误识别，提高追踪稳定性和准确性。


**自写追踪**：有些时候 Tracker 追踪满足不了我们的需求（比如我们需要识别整个线，或者 Tracekr 追踪算法不太适合实验等），我们可以使用 Python/OpenCV 自己写程序进行图像追踪，虽然相比于 Tracker 会比较复杂，但可以使用更灵活多样的算法，如颜色追踪、轮廓识别、圆检测、模板匹配、光流、特征点追踪等，同时也可以进行批量处理大量视频.

## 文献收集和整理

**Zotero**：个人比较喜欢的一个文献管理软件，可以从浏览器或者下载的 PDF 直接保存和读取论文信息，并自动管理作者、期刊、年份、DOI 等信息，还可以直接生成正确格式的参考文献. 这里市面上同样有很多类似的文献管理软件，如 EndNote 等，这里不做过多赘述.

## 自动化控制

**Arduino**：PT 实验中非常常用的微控制器平台，适合完成电机控制、定时、LED/激光控制等自动化任务.  常见的应用包括：

- 电机控制：步进电机，机械手舵机，伺服电机等
- 传感器数据读取
- 设备控制，如激光器功率调制

## 3D 建模

**Fusion 360**：个人比较喜欢使用的一个 3D 建模软件，非常适合 PT 中实验装置、夹具、支架和 3D 打印零件设计. 当然这个市面上有很多类似的软件，比如 Autodesk、Solidworks 等，这里不做过多赘述.

## 杂七杂八

**LaTeX**：严格来说这个不算软件(虽然确实有 LaTeX 这一个排版软件)，这里指的是其对应的公式语法，LaTeX 公式语法基本已经成为行业标准，Origin 公式，AI 输出和输入的公式都是 LaTeX 公式的格式，Office 等的公式输入等基本兼容 LaTeX 公式的语法，因此建议学习基本的公式输入（希腊字母，上下标，求和等特殊符号，正体粗体花体等）方便各种情况的公式输入，以及和 AI 交流时的公式输入. 

**Audition**：主要用于声音录制和频谱分析. PT 中如果实验涉及声音相关的研究，基本需要了解 Au 相关的使用，软件中可以用于查看时域波形和频谱，也可以用于简单的音频滤波和降噪

**FFmpeg**：非常实用的命令行音视频处理工具. 实验和报告中很多视频需要重新转码，个人一般直接使用 FFmpeg 命令行进行批量处理.

**Phyphox**：手机上的一个软件，可以直接读取手机内置的加速度计、陀螺仪、磁力计、气压计、光传感器、麦克风等传感器的数据. 对于 PT 中的一些定性实验或者前期探索非常方便，例如可以直接测量加速度、角速度、磁场、声音频谱以及气压变化等. 数据可以导出到电脑进行进一步处理.
